### ISSUE TITLE
Make it full screen

### ISSUE THREAD

**Issue by Dun-sin** [Ansh-Rathod/My-Portfolio-Next-Js#1]
It doesn't look good that the landing page doesn't take the whole width

![image](https://user-images.githubusercontent.com/78784850/193207642-a2724bcc-9612-40b6-b293-6284be5d7c91.png)

**Comment by Ansh-Rathod** [comment]
thanks! for bringing up the issue. I don't work more on the desktop so this maybe I forgot to resolve. but you can test it again and I made a quick fix for the issue.
B.T.W. you took this screen shot using edge web capture?

**Comment by Dun-sin** [comment]
I used windows default screen shot
Ctrl + shift + s

**Comment by Ansh-Rathod** [comment]
I don't know but maybe the backdrop blur property is not adopted in the screenshot.

**Comment by Ansh-Rathod** [comment]
a white overlay with backdrop blur not working in screenshots.  have to check it
